### PR TITLE
Updates to default configuration

### PR DESCRIPTION
**Pull request by trentusus**
- Added  MAIN_CONTAINER_NAME=localstack-main as recommended by localstack config validate
- Added default hocon file for lake loader so that directory is not created. Defaulting to iceberg lake loader

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by trentusus** [comment]
@miike pull request here

**Comment by trentusus** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @trentusus has signed the Contributor License Agreement. Thanks so much.

**Review by miike — APPROVED** [review]

**Pull request merged**
